teams = [
    {'team_id': 'atlanta-hawks', 'abbreviation': 'ATL', 'active': True, 'first_name': 'Atlanta', 'last_name': 'Hawks', 'conference': 'East', 'division': 'Southeast', 'site_name': 'Philips Arena', 'city': 'Atlanta', 'state': 'Georgia', 'full_name': 'Atlanta Hawks'},
    {'team_id': 'boston-celtics', 'abbreviation': 'BOS', 'active': True, 'first_name': 'Boston', 'last_name': 'Celtics', 'conference': 'East', 'division': 'Atlantic', 'site_name': 'TD Garden', 'city': 'Boston', 'state': 'Massachusetts', 'full_name': 'Boston Celtics'},
    {'team_id': 'brooklyn-nets', 'abbreviation': 'BKN', 'active': True, 'first_name': 'Brooklyn', 'last_name': 'Nets', 'conference': 'East', 'division': 'Atlantic', 'site_name': 'Barclays Center', 'city': 'Brooklyn', 'state': 'New York', 'full_name': 'Brooklyn Nets'},
    {'team_id': 'charlotte-hornets', 'abbreviation': 'CHA', 'active': True, 'first_name': 'Charlotte', 'last_name': 'Hornets', 'conference': 'East', 'division': 'Southeast', 'site_name': 'Time Warner Cable Arena', 'city': 'Charlotte', 'state': 'North Carolina', 'full_name': 'Charlotte Hornets'},
    {'team_id': 'chicago-bulls', 'abbreviation': 'CHI', 'active': True, 'first_name': 'Chicago', 'last_name': 'Bulls', 'conference': 'East', 'division': 'Central', 'site_name': 'United Center', 'city': 'Chicago', 'state': 'Illinois', 'full_name': 'Chicago Bulls'},
    {'team_id': 'cleveland-cavaliers', 'abbreviation': 'CLE', 'active': True, 'first_name': 'Cleveland', 'last_name': 'Cavaliers', 'conference': 'East', 'division': 'Central', 'site_name': 'Quicken Loans Arena', 'city': 'Cleveland', 'state': 'Ohio', 'full_name': 'Cleveland Cavaliers'},
    {'team_id': 'dallas-mavericks', 'abbreviation': 'DAL', 'active': True, 'first_name': 'Dallas', 'last_name': 'Mavericks', 'conference': 'West', 'division': 'Southwest', 'site_name': 'American Airlines Center', 'city': 'Dallas', 'state': 'Texas', 'full_name': 'Dallas Mavericks'},
    {'team_id': 'denver-nuggets', 'abbreviation': 'DEN', 'active': True, 'first_name': 'Denver', 'last_name': 'Nuggets', 'conference': 'West', 'division': 'Northwest', 'site_name': 'Pepsi Center', 'city': 'Denver', 'state': 'Colorado', 'full_name': 'Denver Nuggets'},
    {'team_id': 'detroit-pistons', 'abbreviation': 'DET', 'active': True, 'first_name': 'Detroit', 'last_name': 'Pistons', 'conference': 'East', 'division': 'Central', 'site_name': 'Little Caesars Arena', 'city': 'Detroit', 'state': 'Michigan', 'full_name': 'Detroit Pistons'},
    {'team_id': 'golden-state-warriors', 'abbreviation': 'GS', 'active': True, 'first_name': 'Golden State', 'last_name': 'Warriors', 'conference': 'West', 'division': 'Pacific', 'site_name': 'Oracle Arena', 'city': 'Oakland', 'state': 'California', 'full_name': 'Golden State Warriors'}, {'team_id': 'houston-rockets', 'abbreviation': 'HOU', 'active': True, 'first_name': 'Houston', 'last_name': 'Rockets', 'conference': 'West', 'division': 'Southwest', 'site_name': 'Toyota Center', 'city': 'Houston', 'state': 'Texas', 'full_name': 'Houston Rockets'},
    {'team_id': 'indiana-pacers', 'abbreviation': 'IND', 'active': True, 'first_name': 'Indiana', 'last_name': 'Pacers', 'conference': 'East', 'division': 'Central', 'site_name': 'Bankers Life Fieldhouse', 'city': 'Indianapolis', 'state': 'Indiana', 'full_name': 'Indiana Pacers'},
    {'team_id': 'los-angeles-clippers', 'abbreviation': 'LAC', 'active': True, 'first_name': 'Los Angeles', 'last_name': 'Clippers', 'conference': 'West', 'division': 'Pacific', 'site_name': 'Staples Center', 'city': 'Los Angeles', 'state': 'California', 'full_name': 'Los Angeles Clippers'},
    {'team_id': 'los-angeles-lakers', 'abbreviation': 'LAL', 'active': True, 'first_name': 'Los Angeles', 'last_name': 'Lakers', 'conference': 'West', 'division': 'Pacific', 'site_name': 'Staples Center', 'city': 'Los Angeles', 'state': 'California', 'full_name': 'Los Angeles Lakers'},
    {'team_id': 'memphis-grizzlies', 'abbreviation': 'MEM', 'active': True, 'first_name': 'Memphis', 'last_name': 'Grizzlies', 'conference': 'West', 'division': 'Southwest', 'site_name': 'FedExForum', 'city': 'Memphis', 'state': 'Tennessee', 'full_name': 'Memphis Grizzlies'},
    {'team_id': 'miami-heat', 'abbreviation': 'MIA', 'active': True, 'first_name': 'Miami', 'last_name': 'Heat', 'conference': 'East', 'division': 'Southeast', 'site_name': 'AmericanAirlines Arena', 'city': 'Miami', 'state': 'Florida', 'full_name': 'Miami Heat'},
    {'team_id': 'milwaukee-bucks', 'abbreviation': 'MIL', 'active': True, 'first_name': 'Milwaukee', 'last_name': 'Bucks', 'conference': 'East', 'division': 'Central', 'site_name': 'Fiserv Forum', 'city': 'Milwaukee', 'state': 'Wisconsin', 'full_name': 'Milwaukee Bucks'},
    {'team_id': 'minnesota-timberwolves', 'abbreviation': 'MIN', 'active': True, 'first_name': 'Minnesota', 'last_name': 'Timberwolves', 'conference': 'West', 'division': 'Northwest', 'site_name': 'Target Center', 'city': 'Minneapolis', 'state': 'Minnesota', 'full_name': 'Minnesota Timberwolves'},
    {'team_id': 'new-orleans-pelicans', 'abbreviation': 'NO', 'active': True, 'first_name': 'New Orleans', 'last_name': 'Pelicans', 'conference': 'West', 'division': 'Southwest', 'site_name': 'Smoothie King Center', 'city': 'New Orleans', 'state': 'Louisiana', 'full_name': 'New Orleans Pelicans'},
    {'team_id': 'new-york-knicks', 'abbreviation': 'NY', 'active': True, 'first_name': 'New York', 'last_name': 'Knicks', 'conference': 'East', 'division': 'Atlantic', 'site_name': 'Madison Square Garden', 'city': 'New York', 'state': 'New York', 'full_name': 'New York Knicks'},
    {'team_id': 'oklahoma-city-thunder', 'abbreviation': 'OKC', 'active': True, 'first_name': 'Oklahoma City', 'last_name': 'Thunder', 'conference': 'West', 'division': 'Northwest', 'site_name': 'Chesapeake Energy Arena', 'city': 'Oklahoma City', 'state': 'Oklahoma', 'full_name': 'Oklahoma City Thunder'},
    {'team_id': 'orlando-magic', 'abbreviation': 'ORL', 'active': True, 'first_name': 'Orlando', 'last_name': 'Magic', 'conference': 'East', 'division': 'Southeast', 'site_name': 'Amway Center', 'city': 'Orlando', 'state': 'Florida', 'full_name': 'Orlando Magic'},
    {'team_id': 'philadelphia-76ers', 'abbreviation': 'PHI', 'active': True, 'first_name': 'Philadelphia', 'last_name': '76ers', 'conference': 'East', 'division': 'Atlantic', 'site_name': 'Wells Fargo Center', 'city': 'Philadelphia', 'state': 'Pennsylvania', 'full_name': 'Philadelphia 76ers'},
    {'team_id': 'phoenix-suns', 'abbreviation': 'PHO', 'active': True, 'first_name': 'Phoenix', 'last_name': 'Suns', 'conference': 'West', 'division': 'Pacific', 'site_name': 'Talking Stick Resort Arena', 'city': 'Phoenix', 'state': 'Arizona', 'full_name': 'Phoenix Suns'},
    {'team_id': 'portland-trail-blazers', 'abbreviation': 'POR', 'active': True, 'first_name': 'Portland', 'last_name': 'Trail Blazers', 'conference': 'West', 'division': 'Northwest', 'site_name': 'Moda Center', 'city': 'Portland', 'state': 'Oregon', 'full_name': 'Portland Trail Blazers'},
    {'team_id': 'sacramento-kings', 'abbreviation': 'SAC', 'active': True, 'first_name': 'Sacramento', 'last_name': 'Kings', 'conference': 'West', 'division': 'Pacific', 'site_name': 'Golden 1 Center', 'city': 'Sacramento', 'state': 'California', 'full_name': 'Sacramento Kings'},
    {'team_id': 'san-antonio-spurs', 'abbreviation': 'SA', 'active': True, 'first_name': 'San Antonio', 'last_name': 'Spurs', 'conference': 'West', 'division': 'Southwest', 'site_name': 'AT&T Center', 'city': 'San Antonio', 'state': 'Texas', 'full_name': 'San Antonio Spurs'},
    {'team_id': 'toronto-raptors', 'abbreviation': 'TOR', 'active': True, 'first_name': 'Toronto', 'last_name': 'Raptors', 'conference': 'East', 'division': 'Atlantic', 'site_name': 'Scotiabank Arena', 'city': 'Toronto', 'state': 'Ontario', 'full_name': 'Toronto Raptors'},
    {'team_id': 'utah-jazz', 'abbreviation': 'UTA', 'active': True, 'first_name': 'Utah', 'last_name': 'Jazz', 'conference': 'West', 'division': 'Northwest', 'site_name': 'Vivint Smart Home Arena', 'city': 'Salt Lake City', 'state': 'Utah', 'full_name': 'Utah Jazz'},
    {'team_id': 'washington-wizards', 'abbreviation': 'WAS', 'active': True, 'first_name': 'Washington', 'last_name': 'Wizards', 'conference': 'East', 'division': 'Southeast', 'site_name': 'Verizon Center', 'city': 'Washington', 'state': 'District of Columbia', 'full_name': 'Washington Wizards'}]

import json

def obj_dict(obj):
    return obj.__dict__

json_string = json.dumps(teams, default=obj_dict)

teamDict = json.loads(json_string)

teamsType = type(json_string)
print(json_string)